name: "Happi File Sync Confluence"
description: "Syncs specified files to target confluence pages"
inputs:
  file-mappings:
    description: |
      JSON object containing Confluence configuration and page mappings.
      Format: {
        "baseUrl": "string",
        "user": "string (optional)",
        "pass": "string (optional)",
        "personalAccessToken": "string (optional)",
        "prefix": "string (optional)",
        "force": "boolean (default: false)",
        "fileRoot": "string (optional)",
         "pages": [
           {
             "pageId": "string",
             "file": "string",
             "title": "string (optional)",
             "spaceKey": "string (optional, required for creating new pages)",
             "parentId": "string (optional, parent page ID for new pages)"
           }
         ]
      }
    required: true
  debug:
    description: "Enable debug logging"
    required: false
    default: "false"
runs:
  using: "node20"
  main: "dist/index.js"
