/**
 * Generate an auto-generated file banner in Confluence storage format
 * @param filePath - Path to the original file
 * @param branch - Git branch/ref (optional)
 * @param commitSha - Git commit SHA (optional)
 * @returns HTML string in Confluence storage format
 */
export function generateAutoGeneratedBanner(
	filePath: string,
	branch?: string,
	commitSha?: string
): string {
	// Get GitHub repository URL from environment variables
	const repository = process.env.GITHUB_REPOSITORY;
	const serverUrl = process.env.GITHUB_SERVER_URL || "https://github.com";

	let fileUrl = "";
	if (repository) {
		// Use the commit SHA if available, otherwise use the branch/ref
		const ref = commitSha || branch || process.env.GITHUB_REF || "main";
		// Remove 'refs/heads/' prefix if present
		const cleanRef = ref.replace(/^refs\/heads\//, "");
		// Encode the file path for URL (encode each segment separately to preserve slashes)
		const encodedFilePath = filePath
			.split("/")
			.map((segment) => encodeURIComponent(segment))
			.join("/");
		fileUrl = `${serverUrl}/${repository}/blob/${cleanRef}/${encodedFilePath}`;
	}

	// Create a styled info panel banner in Confluence storage format
	// Using Confluence's info panel macro for better visibility
	const bannerContent = fileUrl
		? `<p><ac:structured-macro ac:name="info" ac:schema-version="1">
<ac:rich-text-body>
<p><strong>⚠️ Auto-Generated File</strong></p>
<p>This page is automatically generated from a source file in the repository.</p>
<p><a href="${fileUrl}">View original file on GitHub</a></p>
</ac:rich-text-body>
</ac:structured-macro></p>`
		: `<p><ac:structured-macro ac:name="info" ac:schema-version="1">
<ac:rich-text-body>
<p><strong>⚠️ Auto-Generated File</strong></p>
<p>This page is automatically generated from a source file in the repository.</p>
<p>Source file: <code>${filePath}</code></p>
</ac:rich-text-body>
</ac:structured-macro></p>`;

	return bannerContent;
}
