import * as core from "@actions/core";
import { SyncFilesOptions } from "./types";
import { createLogger } from "./utils/logging";
import { generateAutoGeneratedBanner } from "./utils/banner";
import {
	ConfluenceApiClient,
	ConfluencePageCreate,
	ConfluencePageUpdate
} from "./confluence-api";
import { convertToConfluenceStorage } from "./utils/confluence-converter";

export async function syncFiles(options: SyncFilesOptions): Promise<void> {
	const { fileMap, page } = options;
	const { baseUrl, fileRoot } = fileMap;

	const logger = createLogger(core.getInput("debug") === "true", "ConfluenceSync");

	logger.info(`Starting sync for page ${page.pageId}: ${page.file} -> ${page.title || "untitled"}`);

	try {
		// Import filesystem utilities
		const fs = await import("fs/promises");
		const path = await import("path");

		// Check if file exists locally
		const filePath = path.resolve(fileRoot || process.cwd(), page.file);
		logger.info(`Reading file from local filesystem: ${filePath}`);

		try {
			await fs.access(filePath);
		} catch {
			throw new Error(`File ${page.file} not found at ${filePath}`);
		}

		// Read file content
		const fileContent = await fs.readFile(filePath, "utf-8");
		logger.info(`Successfully read file content (${fileContent.length} characters)`);

		// Initialize Confluence API client
		const confluenceClient = new ConfluenceApiClient(
			{
				baseUrl,
				user: fileMap.user,
				pass: fileMap.pass
			},
			core.getInput("debug") === "true"
		);

		// Determine content type based on file extension
		const fileExtension = path.extname(page.file).toLowerCase();
		let contentType: "markdown" | "html" | "plain" = "plain";
		if (fileExtension === ".md" || fileExtension === ".markdown") {
			contentType = "markdown";
		} else if (fileExtension === ".html" || fileExtension === ".htm") {
			contentType = "html";
		}

		// Convert file content to Confluence storage format
		const confluenceContent = convertToConfluenceStorage(fileContent, contentType);
		logger.info(`Converted content to Confluence storage format (${contentType} -> storage)`);

		// Generate and prepend auto-generated banner
		const branch = process.env.GITHUB_REF;
		const commitSha = process.env.GITHUB_SHA;
		const banner = generateAutoGeneratedBanner(page.file, branch, commitSha);
		const contentWithBanner = banner + confluenceContent;
		logger.info("Added auto-generated file banner to content");

		// Try to get existing page
		const existingPage = await confluenceClient.getPage(page.pageId);

		if (existingPage) {
			// Update existing page
			logger.info(`Found existing page "${existingPage.title}". Updating content...`);

			const updateData: ConfluencePageUpdate = {
				id: page.pageId,
				type: "page",
				title: page.title || existingPage.title,
				body: {
					storage: {
						value: contentWithBanner,
						representation: "storage"
					}
				},
				version: {
					number: existingPage.version.number + 1
				}
			};

			const updatedPage = await confluenceClient.updatePage(updateData);
			logger.info(`Successfully updated page "${updatedPage.title}" (ID: ${updatedPage.id})`);
		} else {
			// Page doesn't exist, try to create it if we have space configuration
			if (!page.spaceKey) {
				logger.error(`Page ${page.pageId} not found and cannot create new pages without a space key`);
				logger.info(`To create new pages, add 'spaceKey' to your page configuration`);
				throw new Error(`Page ${page.pageId} not found. Cannot create new pages without space key.`);
			}

			logger.info(`Page ${page.pageId} not found. Creating new page in space ${page.spaceKey}...`);

			const createData: ConfluencePageCreate = {
				type: "page",
				title: page.title || `Untitled Page ${page.pageId}`,
				space: {
					key: page.spaceKey
				},
				body: {
					storage: {
						value: contentWithBanner,
						representation: "storage"
					}
				}
			};

			// Add parent page if specified
			if (page.parentId) {
				createData.ancestors = [{ id: page.parentId }];
				logger.info(`Creating page under parent ${page.parentId}`);
			}

			const createdPage = await confluenceClient.createPage(createData);
			logger.info(`Successfully created new page "${createdPage.title}" (ID: ${createdPage.id})`);

			// Update the pageId in outputs to reflect the actual created page ID
			core.setOutput("page-id", createdPage.id);
		}

		// Set GitHub Actions outputs
		core.setOutput("page-id", page.pageId);
		core.setOutput("page-title", page.title || "untitled");
		core.setOutput("file-path", page.file);
		core.setOutput("status", "success");
	} catch (error) {
		const errorMessage = error instanceof Error ? error.message : String(error);
		logger.error(`Error syncing ${page.file} to Confluence page ${page.pageId}: ${errorMessage}`);

		if (error instanceof Error && error.stack) {
			logger.debug(`Error stack: ${error.stack}`);
		}

		// Set failure outputs
		core.setOutput("status", "failed");
		core.setOutput("error", errorMessage);

		// Re-throw to maintain error behavior
		throw error;
	}
}
